In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv("50_Startups.csv")

In [3]:
pd.DataFrame(dataset)

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [4]:
X = dataset.iloc[:,:-1].values

In [5]:
Y = dataset.iloc[:,-1].values
Y = Y.reshape(Y.size,1)

In [6]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [7]:
LEncdr_X = LabelEncoder()

In [8]:
X[:,-1] = LEncdr_X.fit_transform(X[:,-1])

In [9]:
OneHtEncdr = OneHotEncoder(categorical_features = [3])

In [10]:
X = OneHtEncdr.fit_transform(X).toarray()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)

In [11]:
pd.DataFrame(X)

      0    1    2          3          4          5
0   0.0  0.0  1.0  165349.20  136897.80  471784.10
1   1.0  0.0  0.0  162597.70  151377.59  443898.53
2   0.0  1.0  0.0  153441.51  101145.55  407934.54
3   0.0  0.0  1.0  144372.41  118671.85  383199.62
4   0.0  1.0  0.0  142107.34   91391.77  366168.42
5   0.0  0.0  1.0  131876.90   99814.71  362861.36
6   1.0  0.0  0.0  134615.46  147198.87  127716.82
7   0.0  1.0  0.0  130298.13  145530.06  323876.68
8   0.0  0.0  1.0  120542.52  148718.95  311613.29
9   1.0  0.0  0.0  123334.88  108679.17  304981.62
10  0.0  1.0  0.0  101913.08  110594.11  229160.95
11  1.0  0.0  0.0  100671.96   91790.61  249744.55
12  0.0  1.0  0.0   93863.75  127320.38  249839.44
13  1.0  0.0  0.0   91992.39  135495.07  252664.93
14  0.0  1.0  0.0  119943.24  156547.42  256512.92
15  0.0  0.0  1.0  114523.61  122616.84  261776.23
16  1.0  0.0  0.0   78013.11  121597.55  264346.06
17  0.0  0.0  1.0   94657.16  145077.58  282574.31
18  0.0  1.0  0.0   91749.16  114175.79  294919.57
19  0.0  0.0  1.0   86419.70  153514.11       0.00
20  1.0  0.0  0.0   76253.86  113867.30  298664.47
21  0.0  0.0  1.0   78389.47  153773.43  299737.29
22  0.0  1.0  0.0   73994.56  122782.75  303319.26
23  0.0  1.0  0.0   67532.53  105751.03  304768.73
24  0.0  0.0  1.0   77044.01   99281.34  140574.81
25  1.0  0.0  0.0   64664.71  139553.16  137962.62
26  0.0  1.0  0.0   75328.87  144135.98  134050.07
27  0.0  0.0  1.0   72107.60  127864.55  353183.81
28  0.0  1.0  0.0   66051.52  182645.56  118148.20
29  0.0  0.0  1.0   65605.48  153032.06  107138.38
30  0.0  1.0  0.0   61994.48  115641.28   91131.24
31  0.0  0.0  1.0   61136.38  152701.92   88218.23
32  1.0  0.0  0.0   63408.86  129219.61   46085.25
33  0.0  1.0  0.0   55493.95  103057.49  214634.81
34  1.0  0.0  0.0   46426.07  157693.92  210797.67
35  0.0  0.0  1.0   46014.02   85047.44  205517.64
36  0.0  1.0  0.0   28663.76  127056.21  201126.82
37  1.0  0.0  0.0   44069.95   51283.14  197029.42
38  0.0  0.0  1.0   20229.59   65947.93  185265.10
39  1.0  0.0  0.0   38558.51   82982.09  174999.30
40  1.0  0.0  0.0   28754.33  118546.05  172795.67
41  0.0  1.0  0.0   27892.92   84710.77  164470.71
42  1.0  0.0  0.0   23640.93   96189.63  148001.11
43  0.0  0.0  1.0   15505.73  127382.30   35534.17
44  1.0  0.0  0.0   22177.74  154806.14   28334.72
45  0.0  0.0  1.0    1000.23  124153.04    1903.93
46  0.0  1.0  0.0    1315.46  115816.21  297114.46
47  1.0  0.0  0.0       0.00  135426.92       0.00
48  0.0  0.0  1.0     542.05   51743.15       0.00
49  1.0  0.0  0.0       0.00  116983.80   45173.06

note that we do not need to include all the 3 categorically derived cols as any n-1 of them are defined, so is the last one and hence we exclude one of them

In [12]:
X = X[:,1:]

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train,X_test,Y_train,Y_test  = train_test_split(X,Y,test_size = 0.2,random_state=0)

In [15]:
pd.DataFrame(np.concatenate((X_train,Y_train),axis=1))

      0    1          2          3          4          5
0   1.0  0.0   55493.95  103057.49  214634.81   96778.92
1   0.0  1.0   46014.02   85047.44  205517.64   96479.51
2   1.0  0.0   75328.87  144135.98  134050.07  105733.54
3   0.0  0.0   46426.07  157693.92  210797.67   96712.80
4   1.0  0.0   91749.16  114175.79  294919.57  124266.90
5   1.0  0.0  130298.13  145530.06  323876.68  155752.60
6   1.0  0.0  119943.24  156547.42  256512.92  132602.65
7   0.0  1.0    1000.23  124153.04    1903.93   64926.08
8   0.0  1.0     542.05   51743.15       0.00   35673.41
9   0.0  1.0   65605.48  153032.06  107138.38  101004.64
10  0.0  1.0  114523.61  122616.84  261776.23  129917.04
11  1.0  0.0   61994.48  115641.28   91131.24   99937.59
12  0.0  0.0   63408.86  129219.61   46085.25   97427.84
13  0.0  0.0   78013.11  121597.55  264346.06  126992.93
14  0.0  0.0   23640.93   96189.63  148001.11   71498.49
15  0.0  0.0   76253.86  113867.30  298664.47  118474.03
16  0.0  1.0   15505.73  127382.30   35534.17   69758.98
17  0.0  1.0  120542.52  148718.95  311613.29  152211.77
18  0.0  0.0   91992.39  135495.07  252664.93  134307.35
19  0.0  0.0   64664.71  139553.16  137962.62  107404.34
20  0.0  1.0  131876.90   99814.71  362861.36  156991.12
21  0.0  1.0   94657.16  145077.58  282574.31  125370.37
22  0.0  0.0   28754.33  118546.05  172795.67   78239.91
23  0.0  0.0       0.00  116983.80   45173.06   14681.40
24  0.0  0.0  162597.70  151377.59  443898.53  191792.06
25  1.0  0.0   93863.75  127320.38  249839.44  141585.52
26  0.0  0.0   44069.95   51283.14  197029.42   89949.14
27  0.0  1.0   77044.01   99281.34  140574.81  108552.04
28  0.0  0.0  134615.46  147198.87  127716.82  156122.51
29  1.0  0.0   67532.53  105751.03  304768.73  108733.99
30  1.0  0.0   28663.76  127056.21  201126.82   90708.19
31  0.0  1.0   78389.47  153773.43  299737.29  111313.02
32  0.0  1.0   86419.70  153514.11       0.00  122776.86
33  0.0  0.0  123334.88  108679.17  304981.62  149759.96
34  0.0  0.0   38558.51   82982.09  174999.30   81005.76
35  1.0  0.0    1315.46  115816.21  297114.46   49490.75
36  0.0  1.0  144372.41  118671.85  383199.62  182901.99
37  0.0  1.0  165349.20  136897.80  471784.10  192261.83
38  0.0  0.0       0.00  135426.92       0.00   42559.73
39  0.0  0.0   22177.74  154806.14   28334.72   65200.33

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
MlinReg = LinearRegression()

In [18]:
MlinReg.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [19]:
Y_pred = MlinReg.predict(X_test)

In [20]:
pd.DataFrame(np.concatenate((Y_pred,Y_test,abs(Y_pred-Y_test)),axis=1))

               0          1             2
0  103015.201598  103282.38    267.178402
1  132582.277608  144259.40  11677.122392
2  132447.738452  146121.95  13674.211548
3   71976.098513   77798.83   5822.731487
4  178537.482211  191050.39  12512.907789
5  116161.242302  105008.31  11152.932302
6   67851.692097   81229.06  13377.367903
7   98791.733747   97483.56   1308.173747
8  113969.435330  110352.25   3617.185330
9  167921.065696  166187.94   1733.125696

col0 is Ypred, col1 is Ytest and col2 is the loss function

### Optimising the model

optimising the model using backward elimination

In [21]:
import statsmodels.formula.api as sm

adding a collumn of ones here because the statsmodels library doesnt include the constant term in the regression 
did not need to do this for sklearn methods because they add a constant by themselves

In [22]:
X = np.concatenate((np.ones((X[:,0].size,1)),X),axis=1)

In [23]:
 pd.DataFrame(X)

      0    1    2          3          4          5
0   1.0  0.0  1.0  165349.20  136897.80  471784.10
1   1.0  0.0  0.0  162597.70  151377.59  443898.53
2   1.0  1.0  0.0  153441.51  101145.55  407934.54
3   1.0  0.0  1.0  144372.41  118671.85  383199.62
4   1.0  1.0  0.0  142107.34   91391.77  366168.42
5   1.0  0.0  1.0  131876.90   99814.71  362861.36
6   1.0  0.0  0.0  134615.46  147198.87  127716.82
7   1.0  1.0  0.0  130298.13  145530.06  323876.68
8   1.0  0.0  1.0  120542.52  148718.95  311613.29
9   1.0  0.0  0.0  123334.88  108679.17  304981.62
10  1.0  1.0  0.0  101913.08  110594.11  229160.95
11  1.0  0.0  0.0  100671.96   91790.61  249744.55
12  1.0  1.0  0.0   93863.75  127320.38  249839.44
13  1.0  0.0  0.0   91992.39  135495.07  252664.93
14  1.0  1.0  0.0  119943.24  156547.42  256512.92
15  1.0  0.0  1.0  114523.61  122616.84  261776.23
16  1.0  0.0  0.0   78013.11  121597.55  264346.06
17  1.0  0.0  1.0   94657.16  145077.58  282574.31
18  1.0  1.0  0.0   91749.16  114175.79  294919.57
19  1.0  0.0  1.0   86419.70  153514.11       0.00
20  1.0  0.0  0.0   76253.86  113867.30  298664.47
21  1.0  0.0  1.0   78389.47  153773.43  299737.29
22  1.0  1.0  0.0   73994.56  122782.75  303319.26
23  1.0  1.0  0.0   67532.53  105751.03  304768.73
24  1.0  0.0  1.0   77044.01   99281.34  140574.81
25  1.0  0.0  0.0   64664.71  139553.16  137962.62
26  1.0  1.0  0.0   75328.87  144135.98  134050.07
27  1.0  0.0  1.0   72107.60  127864.55  353183.81
28  1.0  1.0  0.0   66051.52  182645.56  118148.20
29  1.0  0.0  1.0   65605.48  153032.06  107138.38
30  1.0  1.0  0.0   61994.48  115641.28   91131.24
31  1.0  0.0  1.0   61136.38  152701.92   88218.23
32  1.0  0.0  0.0   63408.86  129219.61   46085.25
33  1.0  1.0  0.0   55493.95  103057.49  214634.81
34  1.0  0.0  0.0   46426.07  157693.92  210797.67
35  1.0  0.0  1.0   46014.02   85047.44  205517.64
36  1.0  1.0  0.0   28663.76  127056.21  201126.82
37  1.0  0.0  0.0   44069.95   51283.14  197029.42
38  1.0  0.0  1.0   20229.59   65947.93  185265.10
39  1.0  0.0  0.0   38558.51   82982.09  174999.30
40  1.0  0.0  0.0   28754.33  118546.05  172795.67
41  1.0  1.0  0.0   27892.92   84710.77  164470.71
42  1.0  0.0  0.0   23640.93   96189.63  148001.11
43  1.0  0.0  1.0   15505.73  127382.30   35534.17
44  1.0  0.0  0.0   22177.74  154806.14   28334.72
45  1.0  0.0  1.0    1000.23  124153.04    1903.93
46  1.0  1.0  0.0    1315.46  115816.21  297114.46
47  1.0  0.0  0.0       0.00  135426.92       0.00
48  1.0  0.0  1.0     542.05   51743.15       0.00
49  1.0  0.0  0.0       0.00  116983.80   45173.06

note the first collumn appended which is for the constant term in the regression (reasons stated above)

commencing with backward elimination now

creating the optimal matrix of features

In [24]:
X_opt = X[:,[0,1,2,3,4,5]]

choosing significance level(SL) as 0.05

In [25]:
REG_OLS = sm.OLS(Y,X_opt).fit()

OLS stands for ordinary least squares

In [26]:
REG_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Wed, 24 Jul 2019   Prob (F-statistic):           1.34e-27
Time:                        10:29:11   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.013e+04   6884.820      7.281      0.000    3.62e+04     6.4e+04
x1           198.7888   3371.007      0.059      0.953   -6595.030    6992.607
x2           -41.8870   3256.039     -0.013      0.990   -6604.003    6520.229
x3             0.8060      0.046     17.369      0.000       0.712       0.900
x4            -0.0270      0.052     -0.517      0.608      -0.132       0.078
x5             0.0270      0.017      1.574      0.123      -0.008       0.062
==============================================================================
Omnibus:                       14.782   Durbin-Watson:                   1.283
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.266
Skew:                          -0.948   Prob(JB):                     2.41e-05
Kurtosis:                       5.572   Cond. No.                     1.45e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.45e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

highest p-value is exhibited by x2, hence removing that

In [27]:
X_opt = X[:,[0,1,3,4,5]]

In [28]:
REG_OLS = sm.OLS(Y,X_opt).fit()

In [29]:
REG_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     217.2
Date:                Wed, 24 Jul 2019   Prob (F-statistic):           8.49e-29
Time:                        10:29:11   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1070.
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.011e+04   6647.870      7.537      0.000    3.67e+04    6.35e+04
x1           220.1585   2900.536      0.076      0.940   -5621.821    6062.138
x2             0.8060      0.046     17.606      0.000       0.714       0.898
x3            -0.0270      0.052     -0.523      0.604      -0.131       0.077
x4             0.0270      0.017      1.592      0.118      -0.007       0.061
==============================================================================
Omnibus:                       14.758   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.172
Skew:                          -0.948   Prob(JB):                     2.53e-05
Kurtosis:                       5.563   Cond. No.                     1.40e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

x1 has the highest p value and its above SL

In [30]:
X_opt = X[:,[0,3,4,5]]

In [31]:
REG_OLS = sm.OLS(Y,X_opt).fit()

In [32]:
REG_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     296.0
Date:                Wed, 24 Jul 2019   Prob (F-statistic):           4.53e-30
Time:                        10:29:11   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      46   BIC:                             1066.
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.012e+04   6572.353      7.626      0.000    3.69e+04    6.34e+04
x1             0.8057      0.045     17.846      0.000       0.715       0.897
x2            -0.0268      0.051     -0.526      0.602      -0.130       0.076
x3             0.0272      0.016      1.655      0.105      -0.006       0.060
==============================================================================
Omnibus:                       14.838   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.442
Skew:                          -0.949   Prob(JB):                     2.21e-05
Kurtosis:                       5.586   Cond. No.                     1.40e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

removing new x2

In [33]:
X_opt = X[:,[0,3,5]]

In [34]:
REG_OLS = sm.OLS(Y,X_opt).fit()

In [35]:
REG_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Wed, 24 Jul 2019   Prob (F-statistic):           2.16e-31
Time:                        10:29:11   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.698e+04   2689.933     17.464      0.000    4.16e+04    5.24e+04
x1             0.7966      0.041     19.266      0.000       0.713       0.880
x2             0.0299      0.016      1.927      0.060      -0.001       0.061
==============================================================================
Omnibus:                       14.677   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.161
Skew:                          -0.939   Prob(JB):                     2.54e-05
Kurtosis:                       5.575   Cond. No.                     5.32e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.32e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

note that the p-value of the new x1 is not zero- its just so small that it doesnt show up in the no of preset signigicant digits

note again that including x2 in the last step is questionable and will be discussed further ahead. Just implementing backward elimination now , will mention about improvements later

In [36]:
X_opt = X[:,[0,3]]

In [37]:
REG_OLS = sm.OLS(Y,X_opt).fit()

In [38]:
REG_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     849.8
Date:                Wed, 24 Jul 2019   Prob (F-statistic):           3.50e-32
Time:                        10:29:11   Log-Likelihood:                -527.44
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      48   BIC:                             1063.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.903e+04   2537.897     19.320      0.000    4.39e+04    5.41e+04
x1             0.8543      0.029     29.151      0.000       0.795       0.913
==============================================================================
Omnibus:                       13.727   Durbin-Watson:                   1.116
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               18.536
Skew:                          -0.911   Prob(JB):                     9.44e-05
Kurtosis:                       5.361   Cond. No.                     1.65e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.65e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

note:- similar reasons as to why these are close to zero as mentioned not so long above from here

### Automated implementation of backward elimination

In [50]:
import statsmodels.formula.api as sm
def backElim(X,Y,SL):
    NumOVars = len(X[0])
    for i in range(0,NumOVars):
        Reg_OLS = sm.OLS(Y,X).fit()
        maxval  = max(Reg_OLS.pvalues).astype(float)
        if(maxval<=SL): break
        if(maxval>SL):
            for j in range(0,NumOVars - i):
                if(Reg_OLS.pvalues[j]==maxval):
                    X[:,j] = 0
    return X

NOTE:- the reason why setting the col with max pvalue doesnt interfere with the algorithm is because a constant feature has zero p-value and hence would not contribute to the maxvar

In [51]:
SL = 0.05
X_opt = backElim(X,Y,SL)

In [52]:
pd.DataFrame(X_opt)

      0    1    2          3    4    5
0   1.0  0.0  0.0  165349.20  0.0  0.0
1   1.0  0.0  0.0  162597.70  0.0  0.0
2   1.0  0.0  0.0  153441.51  0.0  0.0
3   1.0  0.0  0.0  144372.41  0.0  0.0
4   1.0  0.0  0.0  142107.34  0.0  0.0
5   1.0  0.0  0.0  131876.90  0.0  0.0
6   1.0  0.0  0.0  134615.46  0.0  0.0
7   1.0  0.0  0.0  130298.13  0.0  0.0
8   1.0  0.0  0.0  120542.52  0.0  0.0
9   1.0  0.0  0.0  123334.88  0.0  0.0
10  1.0  0.0  0.0  101913.08  0.0  0.0
11  1.0  0.0  0.0  100671.96  0.0  0.0
12  1.0  0.0  0.0   93863.75  0.0  0.0
13  1.0  0.0  0.0   91992.39  0.0  0.0
14  1.0  0.0  0.0  119943.24  0.0  0.0
15  1.0  0.0  0.0  114523.61  0.0  0.0
16  1.0  0.0  0.0   78013.11  0.0  0.0
17  1.0  0.0  0.0   94657.16  0.0  0.0
18  1.0  0.0  0.0   91749.16  0.0  0.0
19  1.0  0.0  0.0   86419.70  0.0  0.0
20  1.0  0.0  0.0   76253.86  0.0  0.0
21  1.0  0.0  0.0   78389.47  0.0  0.0
22  1.0  0.0  0.0   73994.56  0.0  0.0
23  1.0  0.0  0.0   67532.53  0.0  0.0
24  1.0  0.0  0.0   77044.01  0.0  0.0
25  1.0  0.0  0.0   64664.71  0.0  0.0
26  1.0  0.0  0.0   75328.87  0.0  0.0
27  1.0  0.0  0.0   72107.60  0.0  0.0
28  1.0  0.0  0.0   66051.52  0.0  0.0
29  1.0  0.0  0.0   65605.48  0.0  0.0
30  1.0  0.0  0.0   61994.48  0.0  0.0
31  1.0  0.0  0.0   61136.38  0.0  0.0
32  1.0  0.0  0.0   63408.86  0.0  0.0
33  1.0  0.0  0.0   55493.95  0.0  0.0
34  1.0  0.0  0.0   46426.07  0.0  0.0
35  1.0  0.0  0.0   46014.02  0.0  0.0
36  1.0  0.0  0.0   28663.76  0.0  0.0
37  1.0  0.0  0.0   44069.95  0.0  0.0
38  1.0  0.0  0.0   20229.59  0.0  0.0
39  1.0  0.0  0.0   38558.51  0.0  0.0
40  1.0  0.0  0.0   28754.33  0.0  0.0
41  1.0  0.0  0.0   27892.92  0.0  0.0
42  1.0  0.0  0.0   23640.93  0.0  0.0
43  1.0  0.0  0.0   15505.73  0.0  0.0
44  1.0  0.0  0.0   22177.74  0.0  0.0
45  1.0  0.0  0.0    1000.23  0.0  0.0
46  1.0  0.0  0.0    1315.46  0.0  0.0
47  1.0  0.0  0.0       0.00  0.0  0.0
48  1.0  0.0  0.0     542.05  0.0  0.0
49  1.0  0.0  0.0       0.00  0.0  0.0

a better way to visualize these changes would be to set the corresponding features to 0 instead of deleting them upon elimination

### Final comments

as in the case of the last variable eliminated(with pvalue 0.06), to make a better decision, we use another method of adjusting R-squares.

Read more from different sources

the corresponding code is mentioned below for latter reference

In [ ]:
        import statsmodels.formula.api as sm
        def backwardElimination(x, SL):
            numVars = len(x[0])
            temp = np.zeros((50,6)).astype(int)
            for i in range(0, numVars):
                regressor_OLS = sm.OLS(y, x).fit()
                maxVar = max(regressor_OLS.pvalues).astype(float)
                adjR_before = regressor_OLS.rsquared_adj.astype(float)
                if maxVar > SL:
                    for j in range(0, numVars - i):
                        if (regressor_OLS.pvalues[j].astype(float) == maxVar):
                            temp[:,j] = x[:, j]
                            x = np.delete(x, j, 1)
                            tmp_regressor = sm.OLS(y, x).fit()
                            adjR_after = tmp_regressor.rsquared_adj.astype(float)
                            if (adjR_before >= adjR_after):
                                x_rollback = np.hstack((x, temp[:,[0,j]]))
                                x_rollback = np.delete(x_rollback, j, 1)
                                print (regressor_OLS.summary())
                                return x_rollback
                            else:
                                continue
            regressor_OLS.summary()
            return x
         
        SL = 0.05
        X_opt = X[:, [0, 1, 2, 3, 4, 5]]
        X_Modeled = backwardElimination(X_opt, SL)